// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm6x4CuqrWvTvgDyQappa6EjYt5Vyos1Y',
    appId: '1:854606753142:web:c92a31793e9397d6901e57',
    messagingSenderId: '854606753142',
    projectId: 'bookself-app-3e26b',
    authDomain: 'bookself-app-3e26b.firebaseapp.com',
    storageBucket: 'bookself-app-3e26b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA01X62FMjbQyRSxLrhmN8EVakmrouiKfE',
    appId: '1:854606753142:android:5e43f1a377ca8b34901e57',
    messagingSenderId: '854606753142',
    projectId: 'bookself-app-3e26b',
    storageBucket: 'bookself-app-3e26b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTupRX4SKyjcClETOEobMb1HoNE8cJXso',
    appId: '1:854606753142:ios:c905da5b14cc1601901e57',
    messagingSenderId: '854606753142',
    projectId: 'bookself-app-3e26b',
    storageBucket: 'bookself-app-3e26b.firebasestorage.app',
    iosBundleId: 'com.couple.bookself.bookselfApp',
  );
}
